//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.ServiceDgitron {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDgitron.IDigitron")]
    public interface IDigitron {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitron/GetData", ReplyAction="http://tempuri.org/IDigitron/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitron/GetData", ReplyAction="http://tempuri.org/IDigitron/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitron/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IDigitron/GetDataUsingDataContractResponse")]
        WebClient.ServiceDgitron.CompositeType GetDataUsingDataContract(WebClient.ServiceDgitron.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitron/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IDigitron/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WebClient.ServiceDgitron.CompositeType> GetDataUsingDataContractAsync(WebClient.ServiceDgitron.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitron/Plus", ReplyAction="http://tempuri.org/IDigitron/PlusResponse")]
        double Plus(int value1, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitron/Plus", ReplyAction="http://tempuri.org/IDigitron/PlusResponse")]
        System.Threading.Tasks.Task<double> PlusAsync(int value1, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitron/Minus", ReplyAction="http://tempuri.org/IDigitron/MinusResponse")]
        double Minus(int value1, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitron/Minus", ReplyAction="http://tempuri.org/IDigitron/MinusResponse")]
        System.Threading.Tasks.Task<double> MinusAsync(int value1, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitron/Mnozi", ReplyAction="http://tempuri.org/IDigitron/MnoziResponse")]
        double Mnozi(int value1, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitron/Mnozi", ReplyAction="http://tempuri.org/IDigitron/MnoziResponse")]
        System.Threading.Tasks.Task<double> MnoziAsync(int value1, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitron/Deli", ReplyAction="http://tempuri.org/IDigitron/DeliResponse")]
        double Deli(int value1, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitron/Deli", ReplyAction="http://tempuri.org/IDigitron/DeliResponse")]
        System.Threading.Tasks.Task<double> DeliAsync(int value1, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitron/OpaCupa", ReplyAction="http://tempuri.org/IDigitron/OpaCupaResponse")]
        string OpaCupa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitron/OpaCupa", ReplyAction="http://tempuri.org/IDigitron/OpaCupaResponse")]
        System.Threading.Tasks.Task<string> OpaCupaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDigitronChannel : WebClient.ServiceDgitron.IDigitron, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DigitronClient : System.ServiceModel.ClientBase<WebClient.ServiceDgitron.IDigitron>, WebClient.ServiceDgitron.IDigitron {
        
        public DigitronClient() {
        }
        
        public DigitronClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DigitronClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DigitronClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DigitronClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WebClient.ServiceDgitron.CompositeType GetDataUsingDataContract(WebClient.ServiceDgitron.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceDgitron.CompositeType> GetDataUsingDataContractAsync(WebClient.ServiceDgitron.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public double Plus(int value1, int value2) {
            return base.Channel.Plus(value1, value2);
        }
        
        public System.Threading.Tasks.Task<double> PlusAsync(int value1, int value2) {
            return base.Channel.PlusAsync(value1, value2);
        }
        
        public double Minus(int value1, int value2) {
            return base.Channel.Minus(value1, value2);
        }
        
        public System.Threading.Tasks.Task<double> MinusAsync(int value1, int value2) {
            return base.Channel.MinusAsync(value1, value2);
        }
        
        public double Mnozi(int value1, int value2) {
            return base.Channel.Mnozi(value1, value2);
        }
        
        public System.Threading.Tasks.Task<double> MnoziAsync(int value1, int value2) {
            return base.Channel.MnoziAsync(value1, value2);
        }
        
        public double Deli(int value1, int value2) {
            return base.Channel.Deli(value1, value2);
        }
        
        public System.Threading.Tasks.Task<double> DeliAsync(int value1, int value2) {
            return base.Channel.DeliAsync(value1, value2);
        }
        
        public string OpaCupa() {
            return base.Channel.OpaCupa();
        }
        
        public System.Threading.Tasks.Task<string> OpaCupaAsync() {
            return base.Channel.OpaCupaAsync();
        }
    }
}
